import type { IUser } from "../auth/types/auth";
import type { IMessage } from "./stores/message.store";

export const mockUsers = [
  {
    _id: "u1",
    name: "Nguyễn Văn A",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    _id: "u2",
    name: "Trần Thị B",
    avatar: "https://i.pravatar.cc/150?img=2",
  },
] as IUser[];

export const mockMessages: IMessage[] = [
  {
    _id: "m1",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Chào buổi sáng mọi người!",
    status: "read",
  },
  {
    _id: "m2",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Chào anh, hôm nay có meeting lúc 9h nhé.",
    reactions: [{ emoji: "👍", userId: "u1" }],
    status: "delivered",
  },
  {
    _id: "m3",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    attachments: [
      {
        _id: "f1",
        name: "design.png",
        type: "image",
        url: "https://picsum.photos/300/200",
      },
    ],
    status: "sent",
  },
  {
    _id: "m4",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Video demo đây nhé",
    attachments: [
      {
        _id: "f2",
        name: "demo.mp4",
        type: "video",
        url: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
      },
    ],
    status: "sending",
  },
  {
    _id: "m5",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Đã push code mới lên branch develop rồi.",
    status: "sent",
  },
  {
    _id: "m6",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Ok anh, để em review.",
    status: "read",
  },
  {
    _id: "m7",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Nhớ check performance nhé.",
    reactions: [{ emoji: "🔥", userId: "u2" }],
    status: "read",
  },
  {
    _id: "m8",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Em vừa commit vài thay đổi nhỏ.",
    status: "sent",
  },
  {
    _id: "m9",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Oke, lát anh merge luôn.",
    status: "delivered",
  },
  {
    _id: "m10",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    attachments: [{ _id: "f3", name: "report.pdf", type: "file", url: "#" }],
    text: "Đây là báo cáo tuần.",
    status: "sent",
  },
  {
    _id: "m11",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Good job!",
    reactions: [{ emoji: "👏", userId: "u1" }],
    status: "read",
  },
  {
    _id: "m12",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Anh check giúp em task #42 với.",
    status: "sent",
  },
  {
    _id: "m13",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Đã done task đó rồi nhé.",
    status: "read",
  },
  {
    _id: "m14",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Tốt quá, cảm ơn anh.",
    status: "delivered",
  },
  {
    _id: "m15",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Anh gửi link meeting:",
    attachments: [
      { _id: "f4", name: "Zoom Link", type: "file", url: "https://zoom.us" },
    ],
    status: "sent",
  },
  {
    _id: "m16",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Em join ngay đây.",
    status: "sending",
  },
  {
    _id: "m17",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Ok, đang chờ.",
    status: "sent",
  },
  {
    _id: "m18",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Anh ơi xem hộ em bug login với.",
    status: "read",
  },
  {
    _id: "m19",
    sender: mockUsers[0],
    createdAt: new Date().toISOString(),
    text: "Để anh check logs server.",
    status: "sent",
  },
  {
    _id: "m20",
    sender: mockUsers[1],
    createdAt: new Date().toISOString(),
    text: "Ok anh.",
    reactions: [{ emoji: "❤️", userId: "u1" }],
    status: "read",
  },
];
